- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml
  tags:
    - deployment

- name: app setup
  # ansible.builtin.import_role:
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs.yaml
  tags:
    - deployment

- name: copy mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client
  ansible.builtin.package:
    name: mongodb-mongosh
    state: present

- name: connnect to mongodb catalogue
  ansible.builtin.command: mongosh {{ MONGODB_HOST }} --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
  register: catalogue_output


- name: load products into mongodb
  ansible.builtin.shell: mongosh --host {{ MONGODB_HOST }} </app/db/master-data.js
  when: catalogue_output.stdout | int < 0

- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: system-setup.yaml
  tags:
    - deployment